name: amoeba2
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - astropy
  - spectral-cube
  - matplotlib
  - cxx-compiler
  - pytensor
  - pymc
  - nutpie
  - pip
  - pip:
    - "amoeba2>=1.1.0"
